<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HMS/CommandPB.proto

namespace Hoymiles;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>symcon.hoymiles.CommandReqDTO</code>
 */
class CommandReqDTO extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string dtu_sn = 1;</code>
     */
    protected $dtu_sn = '';
    /**
     * Generated from protobuf field <code>int32 time = 2;</code>
     */
    protected $time = 0;
    /**
     * Generated from protobuf field <code>int32 action = 3;</code>
     */
    protected $action = 0;
    /**
     * Generated from protobuf field <code>int32 package_now = 4;</code>
     */
    protected $package_now = 0;
    /**
     * Generated from protobuf field <code>int32 err_code = 5;</code>
     */
    protected $err_code = 0;
    /**
     * Generated from protobuf field <code>int64 tid = 6;</code>
     */
    protected $tid = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $dtu_sn
     *     @type int $time
     *     @type int $action
     *     @type int $package_now
     *     @type int $err_code
     *     @type int|string $tid
     * }
     */
    public function __construct($data = NULL) {
        \Hoymiles\CommandPB::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string dtu_sn = 1;</code>
     * @return string
     */
    public function getDtuSn()
    {
        return $this->dtu_sn;
    }

    /**
     * Generated from protobuf field <code>string dtu_sn = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDtuSn($var)
    {
        GPBUtil::checkString($var, True);
        $this->dtu_sn = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 time = 2;</code>
     * @return int
     */
    public function getTime()
    {
        return $this->time;
    }

    /**
     * Generated from protobuf field <code>int32 time = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setTime($var)
    {
        GPBUtil::checkInt32($var);
        $this->time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 action = 3;</code>
     * @return int
     */
    public function getAction()
    {
        return $this->action;
    }

    /**
     * Generated from protobuf field <code>int32 action = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setAction($var)
    {
        GPBUtil::checkInt32($var);
        $this->action = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 package_now = 4;</code>
     * @return int
     */
    public function getPackageNow()
    {
        return $this->package_now;
    }

    /**
     * Generated from protobuf field <code>int32 package_now = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setPackageNow($var)
    {
        GPBUtil::checkInt32($var);
        $this->package_now = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 err_code = 5;</code>
     * @return int
     */
    public function getErrCode()
    {
        return $this->err_code;
    }

    /**
     * Generated from protobuf field <code>int32 err_code = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setErrCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->err_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 tid = 6;</code>
     * @return int|string
     */
    public function getTid()
    {
        return $this->tid;
    }

    /**
     * Generated from protobuf field <code>int64 tid = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTid($var)
    {
        GPBUtil::checkInt64($var);
        $this->tid = $var;

        return $this;
    }

}

