<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HMS/CommandPB.proto

namespace Hoymiles;

class CommandPB
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
å

HMS/CommandPB.protosymcon.hoymiles"²
CommandResDTO
time (
action (
dev_kind (
package_nub (
package_now (
tid (
data (	
es_to_sn (	
mi_to_sn	 (
system_total_a
 (
system_total_b (
system_total_c (
mi_sn_item_a (
mi_sn_item_b (
mi_sn_item_c ("q
CommandReqDTO
dtu_sn (	
time (
action (
package_now (
err_code (
tid (";
ESOperatingStatusMO
es_sn (	
progress_rate (";
MIOperatingStatusMO
mi_sn (
progress_rate ("4
MIErrorStatusMO
mi_sn (

error_code ("
ESSucStatusMO
es_sn (	"4
ESErrorStatusMO
es_sn (	

error_code ("…
CommandStatusReqDTO
dtu_sn (	
time (
action (
package_nub (
package_now (
tid (
es_sns_sucs (	
mi_sns_sucs (
es_sns_failds	 (	
mi_sns_failds
 (A
es_mOperatingStatus (2$.symcon.hoymiles.ESOperatingStatusMOA
mi_mOperatingStatus (2$.symcon.hoymiles.MIOperatingStatusMO9
mi_mErrorStatus (2 .symcon.hoymiles.MIErrorStatusMO5
es_mSucStatus (2.symcon.hoymiles.ESSucStatusMO9
es_mErrorStatus (2 .symcon.hoymiles.ESErrorStatusMO"g
CommandStatusResDTO
time (
action (
package_now (
tid (
err_code (BÊHoymilesâHoymilesbproto3'
        , true);

        static::$is_initialized = true;
    }
}

