<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HMS/CommandPB.proto

namespace Hoymiles;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>symcon.hoymiles.CommandResDTO</code>
 */
class CommandResDTO extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 time = 1;</code>
     */
    protected $time = 0;
    /**
     * Generated from protobuf field <code>int32 action = 2;</code>
     */
    protected $action = 0;
    /**
     * Generated from protobuf field <code>int32 dev_kind = 3;</code>
     */
    protected $dev_kind = 0;
    /**
     * Generated from protobuf field <code>int32 package_nub = 4;</code>
     */
    protected $package_nub = 0;
    /**
     * Generated from protobuf field <code>int32 package_now = 5;</code>
     */
    protected $package_now = 0;
    /**
     * Generated from protobuf field <code>int64 tid = 6;</code>
     */
    protected $tid = 0;
    /**
     * Generated from protobuf field <code>string data = 7;</code>
     */
    protected $data = '';
    /**
     * Generated from protobuf field <code>repeated string es_to_sn = 8;</code>
     */
    private $es_to_sn;
    /**
     * Generated from protobuf field <code>repeated int64 mi_to_sn = 9;</code>
     */
    private $mi_to_sn;
    /**
     * Generated from protobuf field <code>int32 system_total_a = 10;</code>
     */
    protected $system_total_a = 0;
    /**
     * Generated from protobuf field <code>int32 system_total_b = 11;</code>
     */
    protected $system_total_b = 0;
    /**
     * Generated from protobuf field <code>int32 system_total_c = 12;</code>
     */
    protected $system_total_c = 0;
    /**
     * Generated from protobuf field <code>repeated int64 mi_sn_item_a = 13;</code>
     */
    private $mi_sn_item_a;
    /**
     * Generated from protobuf field <code>repeated int64 mi_sn_item_b = 14;</code>
     */
    private $mi_sn_item_b;
    /**
     * Generated from protobuf field <code>repeated int64 mi_sn_item_c = 15;</code>
     */
    private $mi_sn_item_c;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $time
     *     @type int $action
     *     @type int $dev_kind
     *     @type int $package_nub
     *     @type int $package_now
     *     @type int|string $tid
     *     @type string $data
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $es_to_sn
     *     @type array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $mi_to_sn
     *     @type int $system_total_a
     *     @type int $system_total_b
     *     @type int $system_total_c
     *     @type array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $mi_sn_item_a
     *     @type array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $mi_sn_item_b
     *     @type array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $mi_sn_item_c
     * }
     */
    public function __construct($data = NULL) {
        \Hoymiles\CommandPB::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 time = 1;</code>
     * @return int
     */
    public function getTime()
    {
        return $this->time;
    }

    /**
     * Generated from protobuf field <code>int32 time = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setTime($var)
    {
        GPBUtil::checkInt32($var);
        $this->time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 action = 2;</code>
     * @return int
     */
    public function getAction()
    {
        return $this->action;
    }

    /**
     * Generated from protobuf field <code>int32 action = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setAction($var)
    {
        GPBUtil::checkInt32($var);
        $this->action = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 dev_kind = 3;</code>
     * @return int
     */
    public function getDevKind()
    {
        return $this->dev_kind;
    }

    /**
     * Generated from protobuf field <code>int32 dev_kind = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setDevKind($var)
    {
        GPBUtil::checkInt32($var);
        $this->dev_kind = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 package_nub = 4;</code>
     * @return int
     */
    public function getPackageNub()
    {
        return $this->package_nub;
    }

    /**
     * Generated from protobuf field <code>int32 package_nub = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setPackageNub($var)
    {
        GPBUtil::checkInt32($var);
        $this->package_nub = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 package_now = 5;</code>
     * @return int
     */
    public function getPackageNow()
    {
        return $this->package_now;
    }

    /**
     * Generated from protobuf field <code>int32 package_now = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setPackageNow($var)
    {
        GPBUtil::checkInt32($var);
        $this->package_now = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 tid = 6;</code>
     * @return int|string
     */
    public function getTid()
    {
        return $this->tid;
    }

    /**
     * Generated from protobuf field <code>int64 tid = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTid($var)
    {
        GPBUtil::checkInt64($var);
        $this->tid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string data = 7;</code>
     * @return string
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>string data = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkString($var, True);
        $this->data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string es_to_sn = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEsToSn()
    {
        return $this->es_to_sn;
    }

    /**
     * Generated from protobuf field <code>repeated string es_to_sn = 8;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEsToSn($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->es_to_sn = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int64 mi_to_sn = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMiToSn()
    {
        return $this->mi_to_sn;
    }

    /**
     * Generated from protobuf field <code>repeated int64 mi_to_sn = 9;</code>
     * @param array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMiToSn($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->mi_to_sn = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 system_total_a = 10;</code>
     * @return int
     */
    public function getSystemTotalA()
    {
        return $this->system_total_a;
    }

    /**
     * Generated from protobuf field <code>int32 system_total_a = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setSystemTotalA($var)
    {
        GPBUtil::checkInt32($var);
        $this->system_total_a = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 system_total_b = 11;</code>
     * @return int
     */
    public function getSystemTotalB()
    {
        return $this->system_total_b;
    }

    /**
     * Generated from protobuf field <code>int32 system_total_b = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setSystemTotalB($var)
    {
        GPBUtil::checkInt32($var);
        $this->system_total_b = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 system_total_c = 12;</code>
     * @return int
     */
    public function getSystemTotalC()
    {
        return $this->system_total_c;
    }

    /**
     * Generated from protobuf field <code>int32 system_total_c = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setSystemTotalC($var)
    {
        GPBUtil::checkInt32($var);
        $this->system_total_c = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int64 mi_sn_item_a = 13;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMiSnItemA()
    {
        return $this->mi_sn_item_a;
    }

    /**
     * Generated from protobuf field <code>repeated int64 mi_sn_item_a = 13;</code>
     * @param array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMiSnItemA($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->mi_sn_item_a = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int64 mi_sn_item_b = 14;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMiSnItemB()
    {
        return $this->mi_sn_item_b;
    }

    /**
     * Generated from protobuf field <code>repeated int64 mi_sn_item_b = 14;</code>
     * @param array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMiSnItemB($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->mi_sn_item_b = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int64 mi_sn_item_c = 15;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMiSnItemC()
    {
        return $this->mi_sn_item_c;
    }

    /**
     * Generated from protobuf field <code>repeated int64 mi_sn_item_c = 15;</code>
     * @param array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMiSnItemC($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->mi_sn_item_c = $arr;

        return $this;
    }

}

