<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HMS/RealData.proto

namespace Hoymiles;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>symcon.hoymiles.MeterMO</code>
 */
class MeterMO extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 type = 1;</code>
     */
    protected $type = 0;
    /**
     * Generated from protobuf field <code>int64 sn = 2;</code>
     */
    protected $sn = 0;
    /**
     * Generated from protobuf field <code>int32 p_tt = 3;</code>
     */
    protected $p_tt = 0;
    /**
     * Generated from protobuf field <code>int32 p_tta = 4;</code>
     */
    protected $p_tta = 0;
    /**
     * Generated from protobuf field <code>int32 p_ttb = 5;</code>
     */
    protected $p_ttb = 0;
    /**
     * Generated from protobuf field <code>int32 p_ttc = 6;</code>
     */
    protected $p_ttc = 0;
    /**
     * Generated from protobuf field <code>int32 pf_tt = 7;</code>
     */
    protected $pf_tt = 0;
    /**
     * Generated from protobuf field <code>int32 ep_tt = 8;</code>
     */
    protected $ep_tt = 0;
    /**
     * Generated from protobuf field <code>int32 ep_tta = 9;</code>
     */
    protected $ep_tta = 0;
    /**
     * Generated from protobuf field <code>int32 ep_ttb = 10;</code>
     */
    protected $ep_ttb = 0;
    /**
     * Generated from protobuf field <code>int32 ep_ttc = 11;</code>
     */
    protected $ep_ttc = 0;
    /**
     * Generated from protobuf field <code>int32 en_tt = 12;</code>
     */
    protected $en_tt = 0;
    /**
     * Generated from protobuf field <code>int32 en_tta = 13;</code>
     */
    protected $en_tta = 0;
    /**
     * Generated from protobuf field <code>int32 en_ttb = 14;</code>
     */
    protected $en_ttb = 0;
    /**
     * Generated from protobuf field <code>int32 en_ttc = 15;</code>
     */
    protected $en_ttc = 0;
    /**
     * Generated from protobuf field <code>int32 fault = 16;</code>
     */
    protected $fault = 0;
    /**
     * Generated from protobuf field <code>int32 u_a = 17;</code>
     */
    protected $u_a = 0;
    /**
     * Generated from protobuf field <code>int32 u_b = 18;</code>
     */
    protected $u_b = 0;
    /**
     * Generated from protobuf field <code>int32 u_c = 19;</code>
     */
    protected $u_c = 0;
    /**
     * Generated from protobuf field <code>int32 i_a = 20;</code>
     */
    protected $i_a = 0;
    /**
     * Generated from protobuf field <code>int32 i_b = 21;</code>
     */
    protected $i_b = 0;
    /**
     * Generated from protobuf field <code>int32 i_c = 22;</code>
     */
    protected $i_c = 0;
    /**
     * Generated from protobuf field <code>int32 pf_a = 23;</code>
     */
    protected $pf_a = 0;
    /**
     * Generated from protobuf field <code>int32 pf_b = 24;</code>
     */
    protected $pf_b = 0;
    /**
     * Generated from protobuf field <code>int32 pf_c = 25;</code>
     */
    protected $pf_c = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $type
     *     @type int|string $sn
     *     @type int $p_tt
     *     @type int $p_tta
     *     @type int $p_ttb
     *     @type int $p_ttc
     *     @type int $pf_tt
     *     @type int $ep_tt
     *     @type int $ep_tta
     *     @type int $ep_ttb
     *     @type int $ep_ttc
     *     @type int $en_tt
     *     @type int $en_tta
     *     @type int $en_ttb
     *     @type int $en_ttc
     *     @type int $fault
     *     @type int $u_a
     *     @type int $u_b
     *     @type int $u_c
     *     @type int $i_a
     *     @type int $i_b
     *     @type int $i_c
     *     @type int $pf_a
     *     @type int $pf_b
     *     @type int $pf_c
     * }
     */
    public function __construct($data = NULL) {
        \Hoymiles\RealData::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>int32 type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkInt32($var);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 sn = 2;</code>
     * @return int|string
     */
    public function getSn()
    {
        return $this->sn;
    }

    /**
     * Generated from protobuf field <code>int64 sn = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSn($var)
    {
        GPBUtil::checkInt64($var);
        $this->sn = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 p_tt = 3;</code>
     * @return int
     */
    public function getPTt()
    {
        return $this->p_tt;
    }

    /**
     * Generated from protobuf field <code>int32 p_tt = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setPTt($var)
    {
        GPBUtil::checkInt32($var);
        $this->p_tt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 p_tta = 4;</code>
     * @return int
     */
    public function getPTta()
    {
        return $this->p_tta;
    }

    /**
     * Generated from protobuf field <code>int32 p_tta = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setPTta($var)
    {
        GPBUtil::checkInt32($var);
        $this->p_tta = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 p_ttb = 5;</code>
     * @return int
     */
    public function getPTtb()
    {
        return $this->p_ttb;
    }

    /**
     * Generated from protobuf field <code>int32 p_ttb = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setPTtb($var)
    {
        GPBUtil::checkInt32($var);
        $this->p_ttb = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 p_ttc = 6;</code>
     * @return int
     */
    public function getPTtc()
    {
        return $this->p_ttc;
    }

    /**
     * Generated from protobuf field <code>int32 p_ttc = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setPTtc($var)
    {
        GPBUtil::checkInt32($var);
        $this->p_ttc = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 pf_tt = 7;</code>
     * @return int
     */
    public function getPfTt()
    {
        return $this->pf_tt;
    }

    /**
     * Generated from protobuf field <code>int32 pf_tt = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setPfTt($var)
    {
        GPBUtil::checkInt32($var);
        $this->pf_tt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 ep_tt = 8;</code>
     * @return int
     */
    public function getEpTt()
    {
        return $this->ep_tt;
    }

    /**
     * Generated from protobuf field <code>int32 ep_tt = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setEpTt($var)
    {
        GPBUtil::checkInt32($var);
        $this->ep_tt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 ep_tta = 9;</code>
     * @return int
     */
    public function getEpTta()
    {
        return $this->ep_tta;
    }

    /**
     * Generated from protobuf field <code>int32 ep_tta = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setEpTta($var)
    {
        GPBUtil::checkInt32($var);
        $this->ep_tta = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 ep_ttb = 10;</code>
     * @return int
     */
    public function getEpTtb()
    {
        return $this->ep_ttb;
    }

    /**
     * Generated from protobuf field <code>int32 ep_ttb = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setEpTtb($var)
    {
        GPBUtil::checkInt32($var);
        $this->ep_ttb = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 ep_ttc = 11;</code>
     * @return int
     */
    public function getEpTtc()
    {
        return $this->ep_ttc;
    }

    /**
     * Generated from protobuf field <code>int32 ep_ttc = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setEpTtc($var)
    {
        GPBUtil::checkInt32($var);
        $this->ep_ttc = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 en_tt = 12;</code>
     * @return int
     */
    public function getEnTt()
    {
        return $this->en_tt;
    }

    /**
     * Generated from protobuf field <code>int32 en_tt = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setEnTt($var)
    {
        GPBUtil::checkInt32($var);
        $this->en_tt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 en_tta = 13;</code>
     * @return int
     */
    public function getEnTta()
    {
        return $this->en_tta;
    }

    /**
     * Generated from protobuf field <code>int32 en_tta = 13;</code>
     * @param int $var
     * @return $this
     */
    public function setEnTta($var)
    {
        GPBUtil::checkInt32($var);
        $this->en_tta = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 en_ttb = 14;</code>
     * @return int
     */
    public function getEnTtb()
    {
        return $this->en_ttb;
    }

    /**
     * Generated from protobuf field <code>int32 en_ttb = 14;</code>
     * @param int $var
     * @return $this
     */
    public function setEnTtb($var)
    {
        GPBUtil::checkInt32($var);
        $this->en_ttb = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 en_ttc = 15;</code>
     * @return int
     */
    public function getEnTtc()
    {
        return $this->en_ttc;
    }

    /**
     * Generated from protobuf field <code>int32 en_ttc = 15;</code>
     * @param int $var
     * @return $this
     */
    public function setEnTtc($var)
    {
        GPBUtil::checkInt32($var);
        $this->en_ttc = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 fault = 16;</code>
     * @return int
     */
    public function getFault()
    {
        return $this->fault;
    }

    /**
     * Generated from protobuf field <code>int32 fault = 16;</code>
     * @param int $var
     * @return $this
     */
    public function setFault($var)
    {
        GPBUtil::checkInt32($var);
        $this->fault = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 u_a = 17;</code>
     * @return int
     */
    public function getUA()
    {
        return $this->u_a;
    }

    /**
     * Generated from protobuf field <code>int32 u_a = 17;</code>
     * @param int $var
     * @return $this
     */
    public function setUA($var)
    {
        GPBUtil::checkInt32($var);
        $this->u_a = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 u_b = 18;</code>
     * @return int
     */
    public function getUB()
    {
        return $this->u_b;
    }

    /**
     * Generated from protobuf field <code>int32 u_b = 18;</code>
     * @param int $var
     * @return $this
     */
    public function setUB($var)
    {
        GPBUtil::checkInt32($var);
        $this->u_b = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 u_c = 19;</code>
     * @return int
     */
    public function getUC()
    {
        return $this->u_c;
    }

    /**
     * Generated from protobuf field <code>int32 u_c = 19;</code>
     * @param int $var
     * @return $this
     */
    public function setUC($var)
    {
        GPBUtil::checkInt32($var);
        $this->u_c = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 i_a = 20;</code>
     * @return int
     */
    public function getIA()
    {
        return $this->i_a;
    }

    /**
     * Generated from protobuf field <code>int32 i_a = 20;</code>
     * @param int $var
     * @return $this
     */
    public function setIA($var)
    {
        GPBUtil::checkInt32($var);
        $this->i_a = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 i_b = 21;</code>
     * @return int
     */
    public function getIB()
    {
        return $this->i_b;
    }

    /**
     * Generated from protobuf field <code>int32 i_b = 21;</code>
     * @param int $var
     * @return $this
     */
    public function setIB($var)
    {
        GPBUtil::checkInt32($var);
        $this->i_b = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 i_c = 22;</code>
     * @return int
     */
    public function getIC()
    {
        return $this->i_c;
    }

    /**
     * Generated from protobuf field <code>int32 i_c = 22;</code>
     * @param int $var
     * @return $this
     */
    public function setIC($var)
    {
        GPBUtil::checkInt32($var);
        $this->i_c = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 pf_a = 23;</code>
     * @return int
     */
    public function getPfA()
    {
        return $this->pf_a;
    }

    /**
     * Generated from protobuf field <code>int32 pf_a = 23;</code>
     * @param int $var
     * @return $this
     */
    public function setPfA($var)
    {
        GPBUtil::checkInt32($var);
        $this->pf_a = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 pf_b = 24;</code>
     * @return int
     */
    public function getPfB()
    {
        return $this->pf_b;
    }

    /**
     * Generated from protobuf field <code>int32 pf_b = 24;</code>
     * @param int $var
     * @return $this
     */
    public function setPfB($var)
    {
        GPBUtil::checkInt32($var);
        $this->pf_b = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 pf_c = 25;</code>
     * @return int
     */
    public function getPfC()
    {
        return $this->pf_c;
    }

    /**
     * Generated from protobuf field <code>int32 pf_c = 25;</code>
     * @param int $var
     * @return $this
     */
    public function setPfC($var)
    {
        GPBUtil::checkInt32($var);
        $this->pf_c = $var;

        return $this;
    }

}

