<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HMS/RealData.proto

namespace Hoymiles;

class RealData
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
¸
HMS/RealData.protosymcon.hoymiles"ò
MeterMO
type (

sn (
p_tt (
p_tta (
p_ttb (
p_ttc (
pf_tt (
ep_tt (
ep_tta	 (
ep_ttb
 (
ep_ttc (
en_tt (
en_tta (
en_ttb (
en_ttc (
fault (
u_a (
u_b (
u_c (
i_a (
i_b (
i_c (
pf_a (
pf_b (
pf_c ("L
RpMO

sn (
sign (
chan (
pv_nub (
link ("m
RSDMO

sn (
ver (	
v (	
p (
temp (
wnum (
crc (
link ("Ç
InverterState

sn (
ver (	
v (
freq (	
p (	
q (	
i (

pf (
temp	 (
wnum
 (
crc (
link (
p_lim (
	mi_signal ("’
TGSMO

sn (
ver (
v_a (
v_b (
v_c (
v_ab (
v_bc (
v_ca (
freq	 (	
p
 (	
q (
i_a (
i_b (
i_c (

pf (
temp (
wnum (
crc (
link (
	mi_signal ("j
	PortState

sn (

pi (	
v (	
i (	
p (

et (

ed (
code ("—
RealDataReqDTO

sn (	
time (

ap (

cp (
ver (-
meter_datas (2.symcon.hoymiles.MeterMO\'
rp_datas (2.symcon.hoymiles.RpMO)
	rsd_datas (2.symcon.hoymiles.RSDMO6
inverter_state	 (2.symcon.hoymiles.InverterState)
	tgs_datas
 (2.symcon.hoymiles.TGSMO.

port_state (2.symcon.hoymiles.PortState
pv_current_power (
pv_daily_yield ("Z
RealDataResDTO
ymd_hms (	

cp (
err_code (
oft (
time (BÊHoymilesâHoymilesbproto3'
        , true);

        static::$is_initialized = true;
    }
}

