<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HMS/RealData.proto

namespace Hoymiles;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>symcon.hoymiles.RealDataReqDTO</code>
 */
class RealDataReqDTO extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string sn = 1;</code>
     */
    protected $sn = '';
    /**
     * Generated from protobuf field <code>int32 time = 2;</code>
     */
    protected $time = 0;
    /**
     * Generated from protobuf field <code>int32 ap = 3;</code>
     */
    protected $ap = 0;
    /**
     * Generated from protobuf field <code>int32 cp = 4;</code>
     */
    protected $cp = 0;
    /**
     * Generated from protobuf field <code>int32 ver = 5;</code>
     */
    protected $ver = 0;
    /**
     * Generated from protobuf field <code>repeated .symcon.hoymiles.MeterMO meter_datas = 6;</code>
     */
    private $meter_datas;
    /**
     * Generated from protobuf field <code>repeated .symcon.hoymiles.RpMO rp_datas = 7;</code>
     */
    private $rp_datas;
    /**
     * Generated from protobuf field <code>repeated .symcon.hoymiles.RSDMO rsd_datas = 8;</code>
     */
    private $rsd_datas;
    /**
     * Generated from protobuf field <code>repeated .symcon.hoymiles.InverterState inverter_state = 9;</code>
     */
    private $inverter_state;
    /**
     * Generated from protobuf field <code>repeated .symcon.hoymiles.TGSMO tgs_datas = 10;</code>
     */
    private $tgs_datas;
    /**
     * Generated from protobuf field <code>repeated .symcon.hoymiles.PortState port_state = 11;</code>
     */
    private $port_state;
    /**
     * [W], factor 0.1
     *
     * Generated from protobuf field <code>uint64 pv_current_power = 12;</code>
     */
    protected $pv_current_power = 0;
    /**
     * [Wh]
     *
     * Generated from protobuf field <code>uint64 pv_daily_yield = 13;</code>
     */
    protected $pv_daily_yield = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $sn
     *     @type int $time
     *     @type int $ap
     *     @type int $cp
     *     @type int $ver
     *     @type array<\Hoymiles\MeterMO>|\Google\Protobuf\Internal\RepeatedField $meter_datas
     *     @type array<\Hoymiles\RpMO>|\Google\Protobuf\Internal\RepeatedField $rp_datas
     *     @type array<\Hoymiles\RSDMO>|\Google\Protobuf\Internal\RepeatedField $rsd_datas
     *     @type array<\Hoymiles\InverterState>|\Google\Protobuf\Internal\RepeatedField $inverter_state
     *     @type array<\Hoymiles\TGSMO>|\Google\Protobuf\Internal\RepeatedField $tgs_datas
     *     @type array<\Hoymiles\PortState>|\Google\Protobuf\Internal\RepeatedField $port_state
     *     @type int|string $pv_current_power
     *           [W], factor 0.1
     *     @type int|string $pv_daily_yield
     *           [Wh]
     * }
     */
    public function __construct($data = NULL) {
        \Hoymiles\RealData::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string sn = 1;</code>
     * @return string
     */
    public function getSn()
    {
        return $this->sn;
    }

    /**
     * Generated from protobuf field <code>string sn = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSn($var)
    {
        GPBUtil::checkString($var, True);
        $this->sn = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 time = 2;</code>
     * @return int
     */
    public function getTime()
    {
        return $this->time;
    }

    /**
     * Generated from protobuf field <code>int32 time = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setTime($var)
    {
        GPBUtil::checkInt32($var);
        $this->time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 ap = 3;</code>
     * @return int
     */
    public function getAp()
    {
        return $this->ap;
    }

    /**
     * Generated from protobuf field <code>int32 ap = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setAp($var)
    {
        GPBUtil::checkInt32($var);
        $this->ap = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 cp = 4;</code>
     * @return int
     */
    public function getCp()
    {
        return $this->cp;
    }

    /**
     * Generated from protobuf field <code>int32 cp = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setCp($var)
    {
        GPBUtil::checkInt32($var);
        $this->cp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 ver = 5;</code>
     * @return int
     */
    public function getVer()
    {
        return $this->ver;
    }

    /**
     * Generated from protobuf field <code>int32 ver = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setVer($var)
    {
        GPBUtil::checkInt32($var);
        $this->ver = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .symcon.hoymiles.MeterMO meter_datas = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMeterDatas()
    {
        return $this->meter_datas;
    }

    /**
     * Generated from protobuf field <code>repeated .symcon.hoymiles.MeterMO meter_datas = 6;</code>
     * @param array<\Hoymiles\MeterMO>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMeterDatas($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Hoymiles\MeterMO::class);
        $this->meter_datas = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .symcon.hoymiles.RpMO rp_datas = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRpDatas()
    {
        return $this->rp_datas;
    }

    /**
     * Generated from protobuf field <code>repeated .symcon.hoymiles.RpMO rp_datas = 7;</code>
     * @param array<\Hoymiles\RpMO>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRpDatas($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Hoymiles\RpMO::class);
        $this->rp_datas = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .symcon.hoymiles.RSDMO rsd_datas = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRsdDatas()
    {
        return $this->rsd_datas;
    }

    /**
     * Generated from protobuf field <code>repeated .symcon.hoymiles.RSDMO rsd_datas = 8;</code>
     * @param array<\Hoymiles\RSDMO>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRsdDatas($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Hoymiles\RSDMO::class);
        $this->rsd_datas = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .symcon.hoymiles.InverterState inverter_state = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getInverterState()
    {
        return $this->inverter_state;
    }

    /**
     * Generated from protobuf field <code>repeated .symcon.hoymiles.InverterState inverter_state = 9;</code>
     * @param array<\Hoymiles\InverterState>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setInverterState($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Hoymiles\InverterState::class);
        $this->inverter_state = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .symcon.hoymiles.TGSMO tgs_datas = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTgsDatas()
    {
        return $this->tgs_datas;
    }

    /**
     * Generated from protobuf field <code>repeated .symcon.hoymiles.TGSMO tgs_datas = 10;</code>
     * @param array<\Hoymiles\TGSMO>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTgsDatas($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Hoymiles\TGSMO::class);
        $this->tgs_datas = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .symcon.hoymiles.PortState port_state = 11;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPortState()
    {
        return $this->port_state;
    }

    /**
     * Generated from protobuf field <code>repeated .symcon.hoymiles.PortState port_state = 11;</code>
     * @param array<\Hoymiles\PortState>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPortState($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Hoymiles\PortState::class);
        $this->port_state = $arr;

        return $this;
    }

    /**
     * [W], factor 0.1
     *
     * Generated from protobuf field <code>uint64 pv_current_power = 12;</code>
     * @return int|string
     */
    public function getPvCurrentPower()
    {
        return $this->pv_current_power;
    }

    /**
     * [W], factor 0.1
     *
     * Generated from protobuf field <code>uint64 pv_current_power = 12;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPvCurrentPower($var)
    {
        GPBUtil::checkUint64($var);
        $this->pv_current_power = $var;

        return $this;
    }

    /**
     * [Wh]
     *
     * Generated from protobuf field <code>uint64 pv_daily_yield = 13;</code>
     * @return int|string
     */
    public function getPvDailyYield()
    {
        return $this->pv_daily_yield;
    }

    /**
     * [Wh]
     *
     * Generated from protobuf field <code>uint64 pv_daily_yield = 13;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPvDailyYield($var)
    {
        GPBUtil::checkUint64($var);
        $this->pv_daily_yield = $var;

        return $this;
    }

}

