<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HMS/RealData.proto

namespace Hoymiles;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>symcon.hoymiles.RSDMO</code>
 */
class RSDMO extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 sn = 1;</code>
     */
    protected $sn = 0;
    /**
     * Generated from protobuf field <code>int32 ver = 2;</code>
     */
    protected $ver = 0;
    /**
     * Generated from protobuf field <code>int32 v = 3;</code>
     */
    protected $v = 0;
    /**
     * Generated from protobuf field <code>int32 p = 4;</code>
     */
    protected $p = 0;
    /**
     * Generated from protobuf field <code>int32 temp = 5;</code>
     */
    protected $temp = 0;
    /**
     * Generated from protobuf field <code>int32 wnum = 6;</code>
     */
    protected $wnum = 0;
    /**
     * Generated from protobuf field <code>int32 crc = 7;</code>
     */
    protected $crc = 0;
    /**
     * Generated from protobuf field <code>int32 link = 8;</code>
     */
    protected $link = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $sn
     *     @type int $ver
     *     @type int $v
     *     @type int $p
     *     @type int $temp
     *     @type int $wnum
     *     @type int $crc
     *     @type int $link
     * }
     */
    public function __construct($data = NULL) {
        \Hoymiles\RealData::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 sn = 1;</code>
     * @return int|string
     */
    public function getSn()
    {
        return $this->sn;
    }

    /**
     * Generated from protobuf field <code>int64 sn = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSn($var)
    {
        GPBUtil::checkInt64($var);
        $this->sn = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 ver = 2;</code>
     * @return int
     */
    public function getVer()
    {
        return $this->ver;
    }

    /**
     * Generated from protobuf field <code>int32 ver = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setVer($var)
    {
        GPBUtil::checkInt32($var);
        $this->ver = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 v = 3;</code>
     * @return int
     */
    public function getV()
    {
        return $this->v;
    }

    /**
     * Generated from protobuf field <code>int32 v = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setV($var)
    {
        GPBUtil::checkInt32($var);
        $this->v = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 p = 4;</code>
     * @return int
     */
    public function getP()
    {
        return $this->p;
    }

    /**
     * Generated from protobuf field <code>int32 p = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setP($var)
    {
        GPBUtil::checkInt32($var);
        $this->p = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 temp = 5;</code>
     * @return int
     */
    public function getTemp()
    {
        return $this->temp;
    }

    /**
     * Generated from protobuf field <code>int32 temp = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setTemp($var)
    {
        GPBUtil::checkInt32($var);
        $this->temp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 wnum = 6;</code>
     * @return int
     */
    public function getWnum()
    {
        return $this->wnum;
    }

    /**
     * Generated from protobuf field <code>int32 wnum = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setWnum($var)
    {
        GPBUtil::checkInt32($var);
        $this->wnum = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 crc = 7;</code>
     * @return int
     */
    public function getCrc()
    {
        return $this->crc;
    }

    /**
     * Generated from protobuf field <code>int32 crc = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setCrc($var)
    {
        GPBUtil::checkInt32($var);
        $this->crc = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 link = 8;</code>
     * @return int
     */
    public function getLink()
    {
        return $this->link;
    }

    /**
     * Generated from protobuf field <code>int32 link = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setLink($var)
    {
        GPBUtil::checkInt32($var);
        $this->link = $var;

        return $this;
    }

}

