<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HMS/RealData.proto

namespace Hoymiles;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>symcon.hoymiles.TGSMO</code>
 */
class TGSMO extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 sn = 1;</code>
     */
    protected $sn = 0;
    /**
     * Generated from protobuf field <code>int32 ver = 2;</code>
     */
    protected $ver = 0;
    /**
     * Generated from protobuf field <code>int32 v_a = 3;</code>
     */
    protected $v_a = 0;
    /**
     * Generated from protobuf field <code>int32 v_b = 4;</code>
     */
    protected $v_b = 0;
    /**
     * Generated from protobuf field <code>int32 v_c = 5;</code>
     */
    protected $v_c = 0;
    /**
     * Generated from protobuf field <code>int32 v_ab = 6;</code>
     */
    protected $v_ab = 0;
    /**
     * Generated from protobuf field <code>int32 v_bc = 7;</code>
     */
    protected $v_bc = 0;
    /**
     * Generated from protobuf field <code>int32 v_ca = 8;</code>
     */
    protected $v_ca = 0;
    /**
     * Generated from protobuf field <code>int32 freq = 9;</code>
     */
    protected $freq = 0;
    /**
     * Generated from protobuf field <code>int32 p = 10;</code>
     */
    protected $p = 0;
    /**
     * Generated from protobuf field <code>int32 q = 11;</code>
     */
    protected $q = 0;
    /**
     * Generated from protobuf field <code>int32 i_a = 12;</code>
     */
    protected $i_a = 0;
    /**
     * Generated from protobuf field <code>int32 i_b = 13;</code>
     */
    protected $i_b = 0;
    /**
     * Generated from protobuf field <code>int32 i_c = 14;</code>
     */
    protected $i_c = 0;
    /**
     * Generated from protobuf field <code>int32 pf = 15;</code>
     */
    protected $pf = 0;
    /**
     * Generated from protobuf field <code>int32 temp = 16;</code>
     */
    protected $temp = 0;
    /**
     * Generated from protobuf field <code>int32 wnum = 17;</code>
     */
    protected $wnum = 0;
    /**
     * Generated from protobuf field <code>int32 crc = 18;</code>
     */
    protected $crc = 0;
    /**
     * Generated from protobuf field <code>int32 link = 19;</code>
     */
    protected $link = 0;
    /**
     * Generated from protobuf field <code>int32 mi_signal = 20;</code>
     */
    protected $mi_signal = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $sn
     *     @type int $ver
     *     @type int $v_a
     *     @type int $v_b
     *     @type int $v_c
     *     @type int $v_ab
     *     @type int $v_bc
     *     @type int $v_ca
     *     @type int $freq
     *     @type int $p
     *     @type int $q
     *     @type int $i_a
     *     @type int $i_b
     *     @type int $i_c
     *     @type int $pf
     *     @type int $temp
     *     @type int $wnum
     *     @type int $crc
     *     @type int $link
     *     @type int $mi_signal
     * }
     */
    public function __construct($data = NULL) {
        \Hoymiles\RealData::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 sn = 1;</code>
     * @return int|string
     */
    public function getSn()
    {
        return $this->sn;
    }

    /**
     * Generated from protobuf field <code>int64 sn = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSn($var)
    {
        GPBUtil::checkInt64($var);
        $this->sn = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 ver = 2;</code>
     * @return int
     */
    public function getVer()
    {
        return $this->ver;
    }

    /**
     * Generated from protobuf field <code>int32 ver = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setVer($var)
    {
        GPBUtil::checkInt32($var);
        $this->ver = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 v_a = 3;</code>
     * @return int
     */
    public function getVA()
    {
        return $this->v_a;
    }

    /**
     * Generated from protobuf field <code>int32 v_a = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setVA($var)
    {
        GPBUtil::checkInt32($var);
        $this->v_a = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 v_b = 4;</code>
     * @return int
     */
    public function getVB()
    {
        return $this->v_b;
    }

    /**
     * Generated from protobuf field <code>int32 v_b = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setVB($var)
    {
        GPBUtil::checkInt32($var);
        $this->v_b = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 v_c = 5;</code>
     * @return int
     */
    public function getVC()
    {
        return $this->v_c;
    }

    /**
     * Generated from protobuf field <code>int32 v_c = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setVC($var)
    {
        GPBUtil::checkInt32($var);
        $this->v_c = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 v_ab = 6;</code>
     * @return int
     */
    public function getVAb()
    {
        return $this->v_ab;
    }

    /**
     * Generated from protobuf field <code>int32 v_ab = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setVAb($var)
    {
        GPBUtil::checkInt32($var);
        $this->v_ab = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 v_bc = 7;</code>
     * @return int
     */
    public function getVBc()
    {
        return $this->v_bc;
    }

    /**
     * Generated from protobuf field <code>int32 v_bc = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setVBc($var)
    {
        GPBUtil::checkInt32($var);
        $this->v_bc = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 v_ca = 8;</code>
     * @return int
     */
    public function getVCa()
    {
        return $this->v_ca;
    }

    /**
     * Generated from protobuf field <code>int32 v_ca = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setVCa($var)
    {
        GPBUtil::checkInt32($var);
        $this->v_ca = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 freq = 9;</code>
     * @return int
     */
    public function getFreq()
    {
        return $this->freq;
    }

    /**
     * Generated from protobuf field <code>int32 freq = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setFreq($var)
    {
        GPBUtil::checkInt32($var);
        $this->freq = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 p = 10;</code>
     * @return int
     */
    public function getP()
    {
        return $this->p;
    }

    /**
     * Generated from protobuf field <code>int32 p = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setP($var)
    {
        GPBUtil::checkInt32($var);
        $this->p = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 q = 11;</code>
     * @return int
     */
    public function getQ()
    {
        return $this->q;
    }

    /**
     * Generated from protobuf field <code>int32 q = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setQ($var)
    {
        GPBUtil::checkInt32($var);
        $this->q = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 i_a = 12;</code>
     * @return int
     */
    public function getIA()
    {
        return $this->i_a;
    }

    /**
     * Generated from protobuf field <code>int32 i_a = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setIA($var)
    {
        GPBUtil::checkInt32($var);
        $this->i_a = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 i_b = 13;</code>
     * @return int
     */
    public function getIB()
    {
        return $this->i_b;
    }

    /**
     * Generated from protobuf field <code>int32 i_b = 13;</code>
     * @param int $var
     * @return $this
     */
    public function setIB($var)
    {
        GPBUtil::checkInt32($var);
        $this->i_b = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 i_c = 14;</code>
     * @return int
     */
    public function getIC()
    {
        return $this->i_c;
    }

    /**
     * Generated from protobuf field <code>int32 i_c = 14;</code>
     * @param int $var
     * @return $this
     */
    public function setIC($var)
    {
        GPBUtil::checkInt32($var);
        $this->i_c = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 pf = 15;</code>
     * @return int
     */
    public function getPf()
    {
        return $this->pf;
    }

    /**
     * Generated from protobuf field <code>int32 pf = 15;</code>
     * @param int $var
     * @return $this
     */
    public function setPf($var)
    {
        GPBUtil::checkInt32($var);
        $this->pf = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 temp = 16;</code>
     * @return int
     */
    public function getTemp()
    {
        return $this->temp;
    }

    /**
     * Generated from protobuf field <code>int32 temp = 16;</code>
     * @param int $var
     * @return $this
     */
    public function setTemp($var)
    {
        GPBUtil::checkInt32($var);
        $this->temp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 wnum = 17;</code>
     * @return int
     */
    public function getWnum()
    {
        return $this->wnum;
    }

    /**
     * Generated from protobuf field <code>int32 wnum = 17;</code>
     * @param int $var
     * @return $this
     */
    public function setWnum($var)
    {
        GPBUtil::checkInt32($var);
        $this->wnum = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 crc = 18;</code>
     * @return int
     */
    public function getCrc()
    {
        return $this->crc;
    }

    /**
     * Generated from protobuf field <code>int32 crc = 18;</code>
     * @param int $var
     * @return $this
     */
    public function setCrc($var)
    {
        GPBUtil::checkInt32($var);
        $this->crc = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 link = 19;</code>
     * @return int
     */
    public function getLink()
    {
        return $this->link;
    }

    /**
     * Generated from protobuf field <code>int32 link = 19;</code>
     * @param int $var
     * @return $this
     */
    public function setLink($var)
    {
        GPBUtil::checkInt32($var);
        $this->link = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 mi_signal = 20;</code>
     * @return int
     */
    public function getMiSignal()
    {
        return $this->mi_signal;
    }

    /**
     * Generated from protobuf field <code>int32 mi_signal = 20;</code>
     * @param int $var
     * @return $this
     */
    public function setMiSignal($var)
    {
        GPBUtil::checkInt32($var);
        $this->mi_signal = $var;

        return $this;
    }

}

