name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout module
        uses: actions/checkout@master
        with:
          submodules: true
      - name: Run tests
        uses: symcon/action-tests@master
